### ISSUE TITLE
Option "bag" is not loaded from config (catmandu.yml)

### ISSUE THREAD

**Issue by jorol** [LibreCat/Catmandu#116]
My config:

``` yml

---
store:
  mdb:
   package: MongoDB
   options:
    database_name: test
    bag: test
  els:
   package: Elasticsearch
   options:
    index_name: test
    bag: test

```

My cmd:

``` terminal
echo {"test":"test"} | catmandu import JSON to mdb
echo {"test":"test"} | catmandu import JSON to els
```

Error:

MongoDB: Data is loaded in default bag/collection "data"
Elasticsearch: "_type" is set to default "data"
