### ISSUE TITLE
Catmandu->store configuration options can only be overwritten one time.

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#325]
I have a catmandu.yml like:

```
---
store:
   foo:
      package: ElasticSearch
      options:
              index_name: foo
```

When in my code do:

```(perl)
  my $store = Catmandu->store('foo');
```

I get a store pointing with `index_name` 'foo'. But when later on in my code I change my mind and want to connect to 'bar':

```(perl)
   $store = Catmandu->store('foo', index_name => 'bar');
```

The store will still point to `index_name' 'foo'. The 'foo' store is cached.
