### ISSUE TITLE
Add a `cossa` fix as inverse of `assoc`

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#348]
```
result:
    name: Albert
    age: 12
```

cossa(result,pairs,key,val)

```
pairs:
  - key: name
    val: Albert
  - key: age
    val: 12

```
