### ISSUE TITLE
Default importer and exporter need to be named explicitly

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#6]
## catmandu.yml:

```
importer:
  default:
    package: YAML
    options:
       file: data.yml
```

code:

```
use Catmandu -load;

Catmandu->importer; # Doesn't work
Catmandu->importer('default'); # works
```
